language: php

php:

  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database homestead;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - composer dump-autoload
  - php artisan db:seed
  - php artisan passport:install
  - sudo npm install
  - gulp
  - php artisan config:cache

script: vendor/bin/phpspec run

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: hhvm
  fast_finish: true